### ISSUE TITLE
Tests need clarifying

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#20]
The end result of the tests is good, but they're a little over-engineered for what they do, and as a result may have been shorter to write, but are much harder to read.

They should be simplified down to look more like normal controller tests.

**Comment by ennukee** [comment]
Is this referring to the tests that generate a list of semantic versions and test them over a loop?

**Comment by dfaulken** [comment]
Sorry, this was referring to the [data controller specs](https://github.com/umts/microservices-engine/blob/master/spec/controllers/data_controller_spec.rb).

**Comment by ennukee** [comment]
Can you point out specific lines? If not the semantic versioning tests, I'm not sure what you're referring to. I think they're fairly easy to read and use basic ruby/rails methodology and the like.

**Comment by ennukee** [comment]
Closing for now unless there's still more that needs clarification.
