### ISSUE TITLE
Semantic versioning logic is nigh impossible to read

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#22]
We've talked about in the past using a library like [semver](https://github.com/flazz/semver), but if that isn't applicable for some reason, we need to again un-over-engineer the code.

**Comment by werebus** [comment]
For that matter you can just use `Gem::Version` (standard library)
to compare version strings:

```ruby
 invalid_cases = [['2.3.2', '1.3.2'], ['1.2.3', '1.1.3'], ['1.2.3', '0.2.3'],
                  ['1.2.3', '1.2.2'], ['1.2.3', '1.1.2'], ['1.2.3', '0.2.3']]

invalid_cases.map{|v| Gem::Version.new(v[1]) < Gem::Version.new(v[0])}.all?
#=>  true
```

**Comment by dfaulken** [comment]
Sure, although @Anbranin aren't sure why all that logic is even there. The (controller) code seems to imply that the router and engine must be the same version, but that seems like it could quickly become a cumbersome restraint: if I want to make a minor change to the router, do I have to publish an empty version change to the engine?

What is the best way to represent the fairly nebulous relationship between "this version of this thing is compatible with these versions of this other thing" when those two pieces of software will never be installed in the same place, and so are not strictly dependent in a way that Bundler et al. can deal with?

What is all of the current logic meant to achieve?
