### ISSUE TITLE
Engine initialization errors should be less generic

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#26]
In https://github.com/umts/microservices-engine/blob/master/lib/generators/install/templates/microservices_engine.rb, we just raise strings. It'd be nicer to use more specific `Exception` objects.

**Comment by ennukee** [comment]
This looks to be fixed now, since we're using `IOError` and `ArgumentError` now?

**Comment by dfaulken** [comment]
I'll leave that call up to you and @Anbranin.

**Comment by ennukee** [comment]
I'll close it for now unless @Anbranin thinks otherwise.
