### ISSUE TITLE
Travis email settings don't work

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#30]
```yml
on_failure: change
```

seems not to work how we think it should, since we just always get emails.

**Comment by werebus** [comment]
The documentation is a bit ambiguous, but it says, "Emails are sent when, **on the given branch**...". (emphasis added) Does that mean that each new failing branch makes a new email, but further failing commits on a PR won't?

**Comment by dfaulken** [comment]
I could've sworn that I've seen emails about each of several successive failing commits on a `master` branch for some of our repos, but perhaps I'm mistaken.

Let's see what happens when #29 is merged.

**Comment by ennukee** [comment]
@dfaulken Fixed?

**Comment by dfaulken** [comment]
Yep, sorry.
