### ISSUE TITLE
To what extent is it worth it to keep old gem versions in the root directory of the app?

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#37]
So far, gems that I've written haven't had more than a few versions.

Perhaps keep just the last three, and keep the others in a folder? Or maybe just the current version is relevant?

**Comment by werebus** [comment]
I'm not entirely sure that you want any artifacts in your source-control. They are entirely reproducible from the git tags, and available on Rubygems.

**Comment by dfaulken** [comment]
Hmm, so gitignore them?
