### ISSUE TITLE
Engine installation process needs to make a migration

### ISSUE THREAD

**Issue by dfaulken** [umts/microservices-engine#40]
Since the engine requires a table to be made in the database of the app it's required in, we need the install process to generate a migration which will create that table.

**Comment by dfaulken** [comment]
Addressed by https://github.com/umts/microservices-engine/commit/627ec492c424651751a769bc536fa262611496a0.

**Comment by dfaulken** [comment]
Some difficulties doing this, see http://stackoverflow.com/questions/41728556/rails-engine-invoking-container-apps-native-migration-generator.

**Comment by dfaulken** [comment]
We got an answer on that question which @Anbranin will check out.

**Comment by Anbranin** [comment]
closeed with 96bfcc4f60ab30b5cb0f57be11bb00228454874a
